name: Bike Point Ingestion

on: 
  schedule: 
    - cron: '*/5 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: des5_bike_point_env
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python/@v4
        with:
          python-version: '3.12.10'

      - name: Install packages
        run: pip install requirements.txt

      - name: Run python script
        env: 
          AWS-ACCESS-KEY: $${{secrets.AWS_ACCESS_KEY}}
          AWS-SECRET-KEY: $${{secrets.AWS_SECRET_KEY}}
          BUCKET-NAME: $${{secrets.BUCKET_NAME}}
        run: python main.py

